Disable clang 12 -Wcompound-token-split-by-macro warning for atomic-v4.h
Otherwise, the macros will in sys/arm/include/atomic-v4.h will result in
warnings (causing -Werror errors), similar to:

arm.arm/tmp/usr/include/machine/atomic-v4.h:125:2: error: '(' and '{'
tokens introducing statement expression appear in different macro
expansion contexts [-Werror,-Wcompound-token-split-by-macro]
        __with_interrupts_disabled(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~

The macros could be restructured to avoid this splitting of statement
expressions, but it is less disruptive to silence the warning for clang
>= 12.

Direct commit to stable/12, since atomic-v4.h is gone (together with
arm.arm) in stable/13 and later.