Add clzdi2 to libsa on mips and powerpc, when built with gcc
Otherwise, several programs that link to libsa will fail with:

/usr/obj/usr/src/powerpc.powerpc/stand/libsa/libsa.a(umoddi3.o): In function `__umodXi3':
/usr/src/contrib/llvm-project/compiler-rt/lib/builtins//int_div_impl.inc:48: undefined reference to `__clzdi2'
/usr/src/contrib/llvm-project/compiler-rt/lib/builtins//int_div_impl.inc:48: undefined reference to `__clzdi2'
/usr/obj/usr/src/powerpc.powerpc/stand/libsa/libsa.a(udivdi3.o): In function `__udivXi3':
/usr/src/contrib/llvm-project/compiler-rt/lib/builtins//int_div_impl.inc:19: undefined reference to `__clzdi2'
/usr/src/contrib/llvm-project/compiler-rt/lib/builtins//int_div_impl.inc:19: undefined reference to `__clzdi2'

This is because base gcc 4.2 fails to inline the __builtin_clzll() calls
in int_div_impl.inc.