Don't attempt to compile files in compiler-rt that crash llvm.
These cause an error like the following (long lines wrapped).

fatal error: error in backend: Cannot select: 0x802a5db10: \
   i64,i64 = srl_parts 0x802a5e710, 0x802a5ee10, 0x802a5e310 [ORD=19] [ID=13]
 0x802a5e710: i64,ch = CopyFromReg 0x8029f1fb8, 0x802a5e210 [ORD=19] [ID=9]
  0x802a5e210: i64 = Register %vreg5 [ID=4]
 0x802a5ee10: i64 = Constant<0> [ID=5]
 0x802a5e310: i64 = zero_extend 0x802a5d210 [ORD=19] [ID=12]
  0x802a5d210: i32 = sub 0x802a5c010, 0x802a5d710 [ORD=17] [ID=11]
   0x802a5c010: i32 = Constant<1075> [ID=1]
   0x802a5d710: i32 = AssertSext 0x802a5c910, 0x802a5c310 [ORD=17] [ID=10]
    0x802a5c910: i32,ch = CopyFromReg 0x8029f1fb8, 0x802a5e610 [ORD=17] [ID=8]
     0x802a5e610: i32 = Register %vreg1 [ID=2]
In function: __fixdfti