bsdinstall: wlanconfig: properly format regdomain dialog input
Without the extra '\n' the dual-column ('REGD' '') are not properly
separated for dialog which leads to an [misleading] error hidden on
the command line:
	Error: --menu bad arguments items number.
[Writing this I wonder why the dual-column input is needed].

It is still unclear as to where the error message quoted in PR287538
suddenly came from for 14.3-RELEASE given the code was broken since 2016
(or noone ever noticed or reported).

Looking at manual ifconfig output:
    ifconfig wlan0 country GB regdomain Expected
    -> ifconfig: unknown regdomain Expected
and "ifconfig: " gets stripped by the script, which means the regdomain
variable would have to be set to "Expected" or more likely to
"Expected eval: Use: not found" which looks like a concatination of
errors.

Sponsored by:	The FreeBSD Foundation
Fixes:		95ee591e83a91
PR:		287538
Reviewed by:	emaste, thj
Differential Revision: https://reviews.freebsd.org/D51313

(cherry picked from commit 5a1e2927d63ed6394b767088eb2d66676f275467)