sdhci_fdt_rockchip: Move ofw_bus_status_okay check
This fixes a warning from GCC:

sys/dev/sdhci/sdhci_fdt_rockchip.c: In function 'sdhci_fdt_rockchip_probe':
sys/dev/sdhci/sdhci_fdt_rockchip.c:120:14: error: statement will never be executed [-Werror=switch-unreachable]
  120 |         if (!ofw_bus_status_okay(dev))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~

Reviewed by:	bnovkov, imp, emaste
Differential Revision:	https://reviews.freebsd.org/D55158

(cherry picked from commit efdd30c94e0ac4007b52b6f40afdab52fecf2aa5)