Fix misleading indentation warning:
libexec/rshd/rshd.c:442:5: error: misleading indentation; statement is not part of the previous 'else' [-Werror,-Wmisleading-indentation]
                                ioctl(pv[0], FIONBIO, (char *)&one);
                                ^
libexec/rshd/rshd.c:440:4: note: previous statement is here
                        else
                        ^

Direct commit to stable/11, since rshd has been removed from FreeBSD 12
and later.