Fix unused variable warning in ipsec_mbuf.c
With clang 15, the following -Werror warning is produced:

    sys/netipsec/ipsec_mbuf.c:93:24: error: variable 'alloc' set but not used [-Werror,-Wunused-but-set-variable]
                    int todo, len, done, alloc;
                                         ^

The 'alloc' variable appears to have been a debugging aid that has never
been used for anything, so remove it.

MFC after:	3 days

(cherry picked from commit df5d2841d507589af0de7301f6cee3d2b98a35be)