openssh: Add ${SKSRCS} to libssh
sshkey.c references sshsk_sign(), which is defined in ${SKSRCS}.

Due to how FreeBSD builds libssh, or put differently, due to upstream
not building a shared libssh.so, we need to partially revert
dca175218f1b ("secure: Adapt Makefile to ssh-sk-client everywhere"), and
add ${SKSRCS} back, to avoid linking problems, especially when building
with GCC:

    /usr/local/bin/ld:
    /usr/obj/usr/src/amd64.amd64/secure/lib/libssh/libprivatessh.so:
    undefined reference to `sshsk_sign'
    collect2: error: ld returned 1 exit status`

Put the sources in a separate line, to maintain line-by-line
compatibility with upstream Makefile.in

PR:		286580
Reviewed by:	emaste
Approved by:	emaste (mentor)
Fixes:	dca175218f1b ("secure: Adapt Makefile to ssh-sk-client everywhere")
Differential Revision:	https://reviews.freebsd.org/D50020