etc: Avoid duplicate gss files installation
From Cirrus-CI
su user -c "/usr/libexec/flua tools/pkgbase/metalog_reader.lua \
    -c /usr/obj/$(pwd -P)/${TARGET}.${TARGET_ARCH}/worldstage/METALOG"
error: ./etc/gss/mech file repeated with same meta: line 2127,40175
error: ./etc/gss/qop file repeated with same meta: line 2128,40176

Prior to ad7c703534e1 the Heimdal versions were installed via

distribution:
	${_+_}cd ${.CURDIR}/gss; ${MAKE} install

ad7c703534e1 added a conditional for MK_MITKRB5 but also added gss or
gss-krb5 to SUBDIRS, causing these files to be installed twice.

Fixes: ad7c703534e1 ("etc/gss: Add MIT GSS glue")
Event:		Kitchener-Waterloo Hackathon 202506
Sponsored by:	The FreeBSD Foundation