Fix misleading indentation warning:
sys/dev/urtwn/if_urtwn.c:4183:4: error: misleading indentation; statement is not part of the previous 'for' [-Werror,-Wmisleading-indentation]
                        if (error != USB_ERR_NORMAL_COMPLETION)
                        ^
sys/dev/urtwn/if_urtwn.c:4180:3: note: previous statement is here
                for (i = 0; i < nitems(rtl8192cu_mac); i++)
                ^

Direct commit to stable/11, since urtwn(4) has been merged into rtwn(4)
in FreeBSD 12 and later (and this code is not in rtwn).