Fix unused variable warning in tcp_hpts.c
With clang 15, the following -Werror warning is produced:

    sys/netinet/tcp_hpts.c:1114:10: error: variable 'paced_cnt' set but not used [-Werror,-Wunused-but-set-variable]
            int32_t paced_cnt = 0;
                    ^

The 'paced_cnt' variable was in tcp_hpts.c when it was first added, but
it appears to have been a debugging aid that has never been used, so
remove it.

MFC after:	3 days

(cherry picked from commit b33bfe6e157429ad764e9a883a5e3a194a6d1f9f)