contrib/bc: fix build with GCC
Building with GCC failed with the following error message:

 error: to be safe all intermediate pointers in cast from 'char **'
 to 'const char **' must be 'const' qualified [-Werror=cast-qual]

This was caused by main() being declared with "char *argv[]" as the
3rd parameter, but argv later being passed cast to "const char**":

113 |     if (BC_IS_BC) s = bc_main(argc, (const char**) argv);
    |                                      ^

This is fixed by declaring the 3rd parameter of main() as "const
char *argv[]".

Reported by:	CI
MFC after:	3 days

(cherry picked from commit ef5752762ba9ec54d5c02023167d24bcdbb45fd7)

vendor/bc: upgrade to version 7.0.1

This update fixes building bc on FreeBSD with non-default compilers
(GCC-12, GCC-13). GCC warned about casting argv from non-const to const
and since warnings are treated as errors, the build failed.

(cherry picked from commit 1e19146fc7692f59e8dfc5da7957e938cd0b81b8)
(cherry picked from commit 5b0dc991093c82824f6fe566af947f64f5072264)